### ISSUE TITLE
rxSolve will not keep more than one covariate in simulation data frame

### ISSUE THREAD

**Issue by zackwjones** [nlmixrdevelopment/RxODE#163]
Hello, 

Is it possible to `keep` more than one covariate in a simulation data frame from iCov? I'm having an issue when I try to keep more than one covariate. 

```r
sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=omegapd,
                 iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                 keep=c("scale_rad","SEX"),Nsub=10)
````

When you view the iCov data frame, it looks fine (i.e., scale_rad column is 3.5 for each ID, and SEX is either 0 or 1), but when you view the sim1 data frame, it has SEX = 3.5 for each ID, and scale_rad is just some random number that is all over the place.

When I do either 

```r
sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=omegapd,
                 iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                 keep="SEX",Nsub=10)
```

or 

```r
sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=omegapd,
                 iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                 keep="scale_rad",Nsub=10)
```

the sim1 data frame looks fine. So, it appears there is an issue with `keep` when you supply it more than one covariate. 

Any thoughts / am I using the wrong syntax?

**Comment by mattfidler** [comment]
Hi @zackwjones 

Thank you for pointing this out to me; 

It is easier for me to parse the issue if I have an example I can reproduce;  One way to do that is with `reprex`:

So for the case that doesn't work (2 covariates) we have:

<details>

``` r
    library(RxODE)
    
    mod <-RxODE({
        C2 = centr/V2;
        C3 = peri/V3;
        KA <- TKA * exp(eta.ka + scale_rad + 0.5 * SEX)
        d/dt(depot) =-KA*depot;
        d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
        d/dt(peri)  =                    Q*C2 - Q*C3;
        d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    });

    theta <- c(TKA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
               Q=1.05E+01,  V3=2.97E+02,              # peripheral
               Kin=1, Kout=1, EC50=200)               # effects

    rdunif <- function(...){
        round(runif(...))
    }

    et(amount.units="mg", time.units="hours") %>%
        et(dose=10000, addl=9, ii=12) %>%
        et(dose=20000, addl=4, time=120,ii=24) %>%
        et(id=1:10) %>%
        et(0:240) ->
        ev3_hum

    sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=lotri(eta.ka ~ 0.01),
                     iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                     keep=c("scale_rad", "SEX"))

    sim1
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Initial Conditions (x$inits): ───────────────────────────────────────────────
#> depot centr  peri   eff 
#>     0     0     0     0 
#> ── First part of data (object): ────────────────────────────────────────────────
#> # A tibble: 2,410 x 11
#>   id     time    C2    C3    KA     depot centr  peri   eff   SEX scale_rad
#>   <fct>   [h] <dbl> <dbl> <dbl>     <dbl> <dbl> <dbl> <dbl> <dbl>     <dbl>
#> 1 1         0   0    0     16.0  1.00e+ 4    0     0  0       3.5         0
#> 2 1         1 127.   5.88  16.0  1.18e- 3 5105. 1745. 0.766   3.5         0
#> 3 1         2  63.0  8.83  16.0 -4.13e-10 2533. 2623. 1.10    3.5         0
#> 4 1         3  32.3 10.1   16.0 -1.89e-11 1300. 3003. 1.16    3.5         0
#> 5 1         4  17.6 10.6   16.0  2.36e- 9  708. 3147. 1.14    3.5         0
#> 6 1         5  10.5 10.7   16.0 -3.94e-10  423. 3179. 1.09    3.5         0
#> # … with 2,404 more rows
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

Which seems to work for me;  Perhaps if I reverse the order:

<details>

``` r
library(RxODE)
    
    mod <-RxODE({
        C2 = centr/V2;
        C3 = peri/V3;
        KA <- TKA * exp(eta.ka + scale_rad + 0.5 * SEX)
        d/dt(depot) =-KA*depot;
        d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
        d/dt(peri)  =                    Q*C2 - Q*C3;
        d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    });

    theta <- c(TKA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
               Q=1.05E+01,  V3=2.97E+02,              # peripheral
               Kin=1, Kout=1, EC50=200)               # effects

    rdunif <- function(...){
        round(runif(...))
    }

    et(amount.units="mg", time.units="hours") %>%
        et(dose=10000, addl=9, ii=12) %>%
        et(dose=20000, addl=4, time=120,ii=24) %>%
        et(id=1:10) %>%
        et(0:240) ->
        ev3_hum

    sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=lotri(eta.ka ~ 0.01),
                     iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                     keep=c("SEX", "scale_rad"))

    sim1
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Initial Conditions (x$inits): ───────────────────────────────────────────────
#> depot centr  peri   eff 
#>     0     0     0     0 
#> ── First part of data (object): ────────────────────────────────────────────────
#> # A tibble: 2,410 x 11
#>   id     time    C2    C3    KA    depot centr  peri   eff scale_rad   SEX
#>   <fct>   [h] <dbl> <dbl> <dbl>    <dbl> <dbl> <dbl> <dbl>     <dbl> <dbl>
#> 1 1         0   0    0     9.10 1.00e+ 4    0     0  0             0     0
#> 2 1         1 132.   5.66  9.10 1.11e+ 0 5290. 1680. 0.768         0     0
#> 3 1         2  65.2  8.73  9.10 1.24e- 4 2622. 2593. 1.10          0     0
#> 4 1         3  33.4 10.1   9.10 1.32e- 8 1343. 2991. 1.17          0     0
#> 5 1         4  18.1 10.6   9.10 1.34e- 9  729. 3143. 1.14          0     0
#> 6 1         5  10.8 10.7   9.10 8.95e-11  433. 3178. 1.10          0     0
#> # … with 2,404 more rows
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

Indeed there seems to be a problem with this;  Actually I think the `keep` was looking for columns in the original dataset, I will have to see what is going on here.

**Comment by mattfidler** [comment]
What is odd for me, is the test runs correctly now.  It seems an intermittent problem.

**Comment by mattfidler** [comment]
It is also clean and checks out with `valgrind`.

**Comment by mattfidler** [comment]
Could you provide a more complete example so I can reproduce this easier?

**Comment by mattfidler** [comment]
I cannot reproduce after adding the protection from R's garbage collection;  Could you try:

```R
devtools::install_github("nlmixrdevelopment/RxODE")
```

It may have been fixed.

**Comment by zackwjones** [comment]
Hi @mattfidler, thank you for the quick responses. 

The title to my issue may have been misleading. Yes, you can `keep` more than one covariate in the simulation data frame, but as you see from your examples, the values are incorrect when you `keep` more than one covariate.

I used the `devtools::install_github("nlmixrdevelopment/RxODE")` suggestion, but I'm still having the same issue where the covariate values are incorrect.

**Comment by mattfidler** [comment]
Can you provide a reproducible example?

**Comment by mattfidler** [comment]
For my example once I fix that I cannot reproduce.

**Comment by mattfidler** [comment]
I can reproduce after reverting; I will try another fix.

**Comment by mattfidler** [comment]
This fix works for me;  Hopefully it works for you;

<details>

``` r
    library(RxODE)

    set.seed(100)

    mod <-RxODE({
        C2 = centr/V2;
        C3 = peri/V3;
        KA <- TKA * exp(eta.ka + scale_rad + 0.5 * SEX)
        d/dt(depot) =-KA*depot;
        d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
        d/dt(peri)  =                    Q*C2 - Q*C3;
        d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    });

    theta <- c(TKA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
               Q=1.05E+01,  V3=2.97E+02,              # peripheral
               Kin=1, Kout=1, EC50=200)               # effects

    rdunif <- function(...){
        round(runif(...))
    }

    et(amount.units="mg", time.units="hours") %>%
        et(dose=10000, addl=9, ii=12) %>%
        et(dose=20000, addl=4, time=120,ii=24) %>%
        et(id=1:10) %>%
        et(0:240) ->
        ev3_hum

    sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=lotri(eta.ka ~ 0.01),
                     iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                     keep=c("SEX", "scale_rad"))

    print(sim1)
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Initial Conditions ($inits): ────────────────────────────────────────────────
#> depot centr  peri   eff 
#>     0     0     0     0 
#> ── First part of data (object): ────────────────────────────────────────────────
#> # A tibble: 2,410 x 11
#>   id     time    C2    C3    KA     depot centr  peri   eff scale_rad   SEX
#>   <fct>   [h] <dbl> <dbl> <dbl>     <dbl> <dbl> <dbl> <dbl>     <dbl> <dbl>
#> 1 1         0   0    0     8.66  1.00e+ 4    0     0  0           3.5     0
#> 2 1         1 132.   5.63  8.66  1.73e+ 0 5313. 1672. 0.768       3.5     0
#> 3 1         2  65.5  8.72  8.66  3.00e- 4 2633. 2590. 1.10        3.5     0
#> 4 1         3  33.5 10.1   8.66  5.23e- 8 1348. 2990. 1.17        3.5     0
#> 5 1         4  18.2 10.6   8.66 -3.94e-10  731. 3143. 1.14        3.5     0
#> 6 1         5  10.8 10.7   8.66  3.23e-11  434. 3178. 1.10        3.5     0
#> # … with 2,404 more rows
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

    print(summary(sim1))
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Summary of Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Model ($model): ─────────────────────────────────────────────────────────────
#> C2=centr/V2;
#> C3=peri/V3;
#> KA=TKA*exp(eta.ka+scale_rad+0.5*SEX);
#> d/dt(depot)=-KA*depot;
#> d/dt(centr)=KA*depot-CL*C2-Q*C2+Q*C3;
#> d/dt(peri)=Q*C2-Q*C3;
#> d/dt(eff)=Kin-Kout*(1-C2/(EC50+C2))*eff;
#>  
#> ── Initial Conditions ($inits): ────────────────────────────────────────────────
#> depot centr  peri   eff 
#>     0     0     0     0 
#> ── Summary of solved data: ─────────────────────────────────────────────────────
#>        id           time           C2               C3              KA        
#>  1      :241   Min.   :  0   Min.   :  0.00   Min.   : 0.00   Min.   : 8.552  
#>  2      :241   1st Qu.: 60   1st Qu.: 13.93   1st Qu.:34.07   1st Qu.: 9.177  
#>  3      :241   Median :120   Median : 16.71   Median :39.55   Median :10.189  
#>  4      :241   Mean   :120   Mean   : 34.51   Mean   :38.07   Mean   :11.426  
#>  5      :241   3rd Qu.:180   3rd Qu.: 27.14   3rd Qu.:45.97   3rd Qu.:14.682  
#>  6      :241   Max.   :240   Max.   :278.31   Max.   :55.57   Max.   :16.407  
#>  (Other):964                                                                  
#>      depot             centr              peri            eff       
#>  Min.   :    0.0   Min.   :    0.0   Min.   :    0   Min.   :0.000  
#>  1st Qu.:    0.0   1st Qu.:  559.9   1st Qu.:10119   1st Qu.:1.073  
#>  Median :    0.0   Median :  671.9   Median :11745   Median :1.091  
#>  Mean   :  829.9   Mean   : 1387.2   Mean   :11306   Mean   :1.170  
#>  3rd Qu.:    0.0   3rd Qu.: 1090.9   3rd Qu.:13652   3rd Qu.:1.215  
#>  Max.   :20000.0   Max.   :11188.3   Max.   :16504   Max.   :1.726  
#>                                                                     
#>    scale_rad        SEX     
#>  Min.   :3.5   Min.   :0.0  
#>  1st Qu.:3.5   1st Qu.:0.0  
#>  Median :3.5   Median :0.0  
#>  Mean   :3.5   Mean   :0.3  
#>  3rd Qu.:3.5   3rd Qu.:1.0  
#>  Max.   :3.5   Max.   :1.0  
#>                             
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> NULL
```

<sup>Created on 2020-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

You can try with:

```r
devtools::install_github("nlmixrdevelopment/RxODE")
```

**Comment by zackwjones** [comment]
Doesn't seem to be fixed. I'm just using the example you posed earlier: 

```r

library(RxODE)

mod <-RxODE({
  C2 = centr/V2;
  C3 = peri/V3;
  KA <- TKA * exp(eta.ka + scale_rad + 0.5 * SEX)
  d/dt(depot) =-KA*depot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
});

theta <- c(TKA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
           Q=1.05E+01,  V3=2.97E+02,              # peripheral
           Kin=1, Kout=1, EC50=200)               # effects

rdunif <- function(...){
  round(runif(...))
}

et(amount.units="mg", time.units="hours") %>%
  et(dose=10000, addl=9, ii=12) %>%
  et(dose=20000, addl=4, time=120,ii=24) %>%
  et(id=1:10) %>%
  et(0:240) ->
  ev3_hum

sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=lotri(eta.ka ~ 0.01),
                 iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                 keep=c("scale_rad", "SEX"))


Solved RxODE object _____________________________
-- Initial Conditions (sim1$inits): --------------------------------------------
depot centr  peri   eff 
    0     0     0     0 
-- First part of data (object): ------------------------------------------------
# A tibble: 2,410 x 11
  id     time    C2    C3    KA     depot centr  peri   eff   SEX scale_rad
  <fct>   [h] <dbl> <dbl> <dbl>     <dbl> <dbl> <dbl> <dbl> <dbl>     <dbl>
1 1         0   0    0     15.9  1.00e+ 4    0     0  0       3.5 4.11e-315
2 1         1 127.   5.88  15.9  1.19e- 3 5105. 1745. 0.766   3.5 7.62e-314
3 1         2  63.0  8.83  15.9 -4.15e-10 2533. 2623. 1.10    3.5 5.71e-311
4 1         3  32.3 10.1   15.9 -1.93e-11 1300. 3003. 1.16    3.5 1.32e-312
5 1         4  17.6 10.6   15.9  2.79e- 9  708. 3147. 1.14    3.5 0.       
6 1         5  10.5 10.7   15.9 -3.23e-10  423. 3179. 1.09    3.5 0.       




````

**Comment by mattfidler** [comment]
Hm.  If you are using Rstudio, please restart and make sure to not load the last workspace.  

This is under:

```
Tools -> Global Options -> General
```

Then make sure `Restore .RData into workspace at startup` is unchecked.  This can load prior versions of `RxODE` and other packages into your workspace (a scary thing when you want to do reproducible research)

Also make sure the installation from:

```R
devtools::install_github("nlmixrdevelopment/RxODE");
```

Is successful.  Then run `devtools::session_info()` after to make sure you grabbed the correct version of `RxODE` from `github`.  

For me this gives:

<details>

``` r
    library(RxODE)
    set.seed(100)

    mod <-RxODE({
        C2 = centr/V2;
        C3 = peri/V3;
        KA <- TKA * exp(eta.ka + scale_rad + 0.5 * SEX)
        d/dt(depot) =-KA*depot;
        d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
        d/dt(peri)  =                    Q*C2 - Q*C3;
        d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    });

    theta <- c(TKA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
               Q=1.05E+01,  V3=2.97E+02,              # peripheral
               Kin=1, Kout=1, EC50=200)               # effects

    rdunif <- function(...){
        round(runif(...))
    }

    et(amount.units="mg", time.units="hours") %>%
        et(dose=10000, addl=9, ii=12) %>%
        et(dose=20000, addl=4, time=120,ii=24) %>%
        et(id=1:10) %>%
        et(0:240) ->
        ev3_hum

    sim1  <- rxSolve(mod,theta,ev=ev3_hum,omega=lotri(eta.ka ~ 0.01),
                     iCov=data.frame(id=1:10, scale_rad=3.5, SEX=rdunif(10,0,1)),
                     keep=c("SEX", "scale_rad"))

    print(sim1)
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ Solved RxODE object ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
#> ── Initial Conditions ($inits): ────────────────────────────────────────────────
#> depot centr  peri   eff 
#>     0     0     0     0 
#> ── First part of data (object): ────────────────────────────────────────────────
#> # A tibble: 2,410 x 11
#>   id     time    C2    C3    KA     depot centr  peri   eff scale_rad   SEX
#>   <fct>   [h] <dbl> <dbl> <dbl>     <dbl> <dbl> <dbl> <dbl>     <dbl> <dbl>
#> 1 1         0   0    0     8.66  1.00e+ 4    0     0  0           3.5     0
#> 2 1         1 132.   5.63  8.66  1.73e+ 0 5313. 1672. 0.768       3.5     0
#> 3 1         2  65.5  8.72  8.66  3.00e- 4 2633. 2590. 1.10        3.5     0
#> 4 1         3  33.5 10.1   8.66  5.23e- 8 1348. 2990. 1.17        3.5     0
#> 5 1         4  18.2 10.6   8.66 -3.94e-10  731. 3143. 1.14        3.5     0
#> 6 1         5  10.8 10.7   8.66  3.23e-11  434. 3178. 1.10        3.5     0
#> # … with 2,404 more rows
#> ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

    devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Gentoo/Linux                
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.utf8                  
#>  ctype    en_US.utf8                  
#>  tz       US/Central                  
#>  date     2020-02-24                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version  date       lib source                                  
#>  assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)                          
#>  backports     1.1.5    2019-10-02 [1] CRAN (R 3.6.0)                          
#>  callr         3.4.0    2019-12-09 [1] CRAN (R 3.6.0)                          
#>  cli           2.0.1    2020-01-08 [1] CRAN (R 3.6.0)                          
#>  colorspace    1.4-1    2019-03-18 [1] CRAN (R 3.6.0)                          
#>  crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)                          
#>  data.table    1.12.8   2019-12-09 [1] CRAN (R 3.6.0)                          
#>  desc          1.2.0    2018-05-01 [1] CRAN (R 3.6.0)                          
#>  devtools      2.2.1    2019-09-24 [1] CRAN (R 3.6.0)                          
#>  digest        0.6.25   2020-02-23 [1] CRAN (R 3.6.0)                          
#>  dparser       0.1.8    2017-11-13 [1] CRAN (R 3.6.0)                          
#>  dplyr         0.8.3    2019-07-04 [1] CRAN (R 3.6.0)                          
#>  ellipsis      0.3.0    2019-09-20 [1] CRAN (R 3.6.0)                          
#>  evaluate      0.14     2019-05-28 [1] CRAN (R 3.6.0)                          
#>  fansi         0.4.1    2020-01-08 [1] CRAN (R 3.6.0)                          
#>  farver        2.0.3    2020-01-16 [1] CRAN (R 3.6.0)                          
#>  fs            1.3.1    2019-05-06 [1] CRAN (R 3.6.0)                          
#>  ggforce       0.3.1    2019-08-20 [1] CRAN (R 3.6.0)                          
#>  ggplot2       3.2.1    2019-08-10 [1] CRAN (R 3.6.0)                          
#>  glue          1.3.1    2019-03-12 [1] CRAN (R 3.6.0)                          
#>  gtable        0.3.0    2019-03-25 [1] CRAN (R 3.6.0)                          
#>  highr         0.8      2019-03-20 [1] CRAN (R 3.6.0)                          
#>  htmltools     0.4.0    2019-10-04 [1] CRAN (R 3.6.0)                          
#>  knitr         1.28     2020-02-06 [1] CRAN (R 3.6.0)                          
#>  lazyeval      0.2.2    2019-03-15 [1] CRAN (R 3.6.0)                          
#>  lifecycle     0.1.0    2019-08-01 [1] CRAN (R 3.6.0)                          
#>  lotri         0.2.2    2020-02-20 [1] local                                   
#>  magrittr      1.5      2014-11-22 [1] CRAN (R 3.6.0)                          
#>  MASS          7.3-51.4 2019-03-31 [2] CRAN (R 3.6.0)                          
#>  memoise       1.1.0    2017-04-21 [1] CRAN (R 3.6.0)                          
#>  munsell       0.5.0    2018-06-12 [1] CRAN (R 3.6.0)                          
#>  mvnfast       0.2.5    2018-01-31 [1] CRAN (R 3.6.0)                          
#>  pillar        1.4.3    2019-12-20 [1] CRAN (R 3.6.0)                          
#>  pkgbuild      1.0.6    2019-10-09 [1] CRAN (R 3.6.0)                          
#>  pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 3.6.0)                          
#>  pkgload       1.0.2    2018-10-29 [1] CRAN (R 3.6.0)                          
#>  polyclip      1.10-0   2019-03-14 [1] CRAN (R 3.6.0)                          
#>  PreciseSums   0.3      2018-04-12 [1] CRAN (R 3.6.0)                          
#>  prettyunits   1.1.0    2020-01-09 [1] CRAN (R 3.6.0)                          
#>  processx      3.4.1    2019-07-18 [1] CRAN (R 3.6.0)                          
#>  ps            1.3.0    2018-12-21 [1] CRAN (R 3.6.0)                          
#>  purrr         0.3.3    2019-10-18 [1] CRAN (R 3.6.0)                          
#>  R6            2.4.1    2019-11-12 [1] CRAN (R 3.6.0)                          
#>  Rcpp          1.0.3    2019-11-08 [1] CRAN (R 3.6.0)                          
#>  remotes       2.1.1    2020-02-15 [1] CRAN (R 3.6.0)                          
#>  rlang         0.4.4    2020-01-28 [1] CRAN (R 3.6.0)                          
#>  rmarkdown     2.1      2020-01-20 [1] CRAN (R 3.6.0)                          
#>  rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.0)                          
#>  RxODE       * 0.9.1-9  2020-02-25 [1] Github (nlmixrdevelopment/RxODE@c69b894)
#>  scales        1.1.0    2019-11-18 [1] CRAN (R 3.6.0)                          
#>  sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.0)                          
#>  stringi       1.4.6    2020-02-17 [1] CRAN (R 3.6.0)                          
#>  stringr       1.4.0    2019-02-10 [1] CRAN (R 3.6.0)                          
#>  sys           3.3      2019-08-21 [1] CRAN (R 3.6.0)                          
#>  testthat      2.3.1    2019-12-01 [1] CRAN (R 3.6.0)                          
#>  tibble        2.1.3    2019-06-06 [1] CRAN (R 3.6.0)                          
#>  tidyselect    1.0.0    2020-01-27 [1] CRAN (R 3.6.0)                          
#>  tweenr        1.0.1    2018-12-14 [1] CRAN (R 3.6.0)                          
#>  units         0.6-5    2019-10-08 [1] CRAN (R 3.6.0)                          
#>  usethis       1.5.1    2019-07-04 [1] CRAN (R 3.6.0)                          
#>  utf8          1.1.4    2018-05-24 [1] CRAN (R 3.6.0)                          
#>  vctrs         0.2.3    2020-02-20 [1] CRAN (R 3.6.0)                          
#>  withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.0)                          
#>  xfun          0.12     2020-01-13 [1] CRAN (R 3.6.0)                          
#>  yaml          2.2.1    2020-02-01 [1] CRAN (R 3.6.0)                          
#> 
#> [1] /home/matt/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/lib64/R/library
```

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

Note the line for `RxODE`:

```
#>  RxODE       * 0.9.1-9  2020-02-25 [1] Github (nlmixrdevelopment/RxODE@c69b894)
````

This should have c69b894 as the revision, which is the version I tested.

I have had other people check as well, and they cannot reproduce now. Additionally the travis/appveyor builds shows that mac osx, windows, and linux all perform this operation correctly with this revision.

**Comment by zackwjones** [comment]
@mattfidler 

Thank you so much for the continued support. Your suggestions on restarting / unchecking `restore .RData` did the trick.

**Comment by mattfidler** [comment]
Thanks for reporting the issue @zackwjones
